#Import('*')
#
#SimObject("Interface_Controller.py", sim_objects=['Interface_Controller'])
#SimObject("Interface_Bridge.py", sim_objects=['InterfaceBridge'])
#
#Source('Interface_Controller.cc')
#Source('Interface_Entry.cc')
#Source('Interface_State.cc')
#Source('Interface_Transitions.cc')
#Source('Interface_Wakeup.cc')
#Source('Interface_Event.cc')
#Source('Interface_TBE.cc')
#
#Source('Interface_Bridge.cc')
#
#DebugFlag('InterfaceBridge', "For bridging two interface controllers")